import firebase_admin
from firebase_admin import credentials, firestore
from datetime import datetime

# Initialize Firebase Admin SDK
cred = credentials.Certificate("serviceAccountKey.json")
firebase_admin.initialize_app(cred)
db = firestore.client()

today_str = datetime.now().strftime("%Y-%m-%d")

students = [
    {
        "address": "123, 1st street, hyderabad",
        "blood_group": "A+",
        "contact": "1234567890",
        "dob": "2013-07-15",
        "email": "priya@example.com",
        "father_contact": "1234567890",
        "father_name": "Rahul Sharma",
        "grade": "Playgroup",
        "joined_date": datetime(2025, 7, 4, 1, 10, 2),
        "mother_contact": "1234567890",
        "mother_name": "Priya Sharma",
        "name": "Rahul Sharma",
        "nick_name": "Rahi",
        "parent_name": "Priya Sharma",
        "profile_image": "",
        "student_id": "STU2025001",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👦",
        "date": today_str
    },
    {
        "address": "456, 2nd street, bangalore",
        "blood_group": "B+",
        "contact": "9876543210",
        "dob": "2012-05-20",
        "email": "arjun@example.com",
        "father_contact": "9876543210",
        "father_name": "Suresh Kumar",
        "grade": "Playgroup",
        "joined_date": datetime(2024, 6, 15, 9, 30, 0),
        "mother_contact": "9876543210",
        "mother_name": "Anita Kumar",
        "name": "Arjun Kumar",
        "nick_name": "Arju",
        "parent_name": "Anita Kumar",
        "profile_image": "",
        "student_id": "STU2025002",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👦",
        "date": today_str
    },
    {
        "address": "789, 3rd street, chennai",
        "blood_group": "O-",
        "contact": "1122334455",
        "dob": "2014-11-10",
        "email": "meera@example.com",
        "father_contact": "1122334455",
        "father_name": "Ramesh Iyer",
        "grade": "Nursery",
        "joined_date": datetime(2023, 8, 1, 14, 0, 0),
        "mother_contact": "1122334455",
        "mother_name": "Lakshmi Iyer",
        "name": "Meera Iyer",
        "nick_name": "Meeru",
        "parent_name": "Lakshmi Iyer",
        "profile_image": "",
        "student_id": "STU2025003",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👧",
        "date": today_str
    },
    {
        "address": "321, 4th street, mumbai",
        "blood_group": "AB+",
        "contact": "5566778899",
        "dob": "2011-03-25",
        "email": "rahul@example.com",
        "father_contact": "5566778899",
        "father_name": "Vikram Singh",
        "grade": "Nursery",
        "joined_date": datetime(2022, 1, 10, 8, 45, 0),
        "mother_contact": "5566778899",
        "mother_name": "Sunita Singh",
        "name": "Rahul Singh",
        "nick_name": "Rahu",
        "parent_name": "Sunita Singh",
        "profile_image": "",
        "student_id": "STU2025004",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👦",
        "date": today_str
    },
    {
        "address": "654, 5th street, delhi",
        "blood_group": "A-",
        "contact": "6677889900",
        "dob": "2013-09-05",
        "email": "anita@example.com",
        "father_contact": "6677889900",
        "father_name": "Rajesh Gupta",
        "grade": "Pre primary I",
        "joined_date": datetime(2023, 3, 20, 10, 15, 0),
        "mother_contact": "6677889900",
        "mother_name": "Sunita Gupta",
        "name": "Anita Gupta",
        "nick_name": "Anu",
        "parent_name": "Sunita Gupta",
        "profile_image": "",
        "student_id": "STU2025005",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👧",
        "date": today_str
    },
    
    {
        "address": "12, Rose Lane, Pune",
        "blood_group": "B-",
        "contact": "9988776655",
        "dob": "2014-08-19",
        "email": "isha@example.com",
        "father_contact": "9988776655",
        "father_name": "Ravi Joshi",
        "grade": "Nursery",
        "joined_date": datetime(2023, 9, 1, 9, 0, 0),
        "mother_contact": "9988776655",
        "mother_name": "Sneha Joshi",
        "name": "Isha Joshi",
        "nick_name": "Ishu",
        "parent_name": "Sneha Joshi",
        "profile_image": "",
        "student_id": "STU2025006",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👧",
        "date": today_str
    },
    {
        "address": "34, Green Street, Ahmedabad",
        "blood_group": "O+",
        "contact": "8899001122",
        "dob": "2015-12-10",
        "email": "veer@example.com",
        "father_contact": "8899001122",
        "father_name": "Nitin Patel",
        "grade": "Playgroup",
        "joined_date": datetime(2024, 5, 10, 11, 0, 0),
        "mother_contact": "8899001122",
        "mother_name": "Kajal Patel",
        "name": "Veer Patel",
        "nick_name": "Veeru",
        "parent_name": "Kajal Patel",
        "profile_image": "",
        "student_id": "STU2025007",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👦",
        "date": today_str
    },
    {
        "address": "76, Blue Sky Apt, Kochi",
        "blood_group": "A+",
        "contact": "7788990011",
        "dob": "2012-04-08",
        "email": "diya@example.com",
        "father_contact": "7788990011",
        "father_name": "Arvind Nair",
        "grade": "Pre primary I",
        "joined_date": datetime(2022, 11, 5, 10, 30, 0),
        "mother_contact": "7788990011",
        "mother_name": "Latha Nair",
        "name": "Diya Nair",
        "nick_name": "Didi",
        "parent_name": "Latha Nair",
        "profile_image": "",
        "student_id": "STU2025008",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👧",
        "date": today_str
    },
    {
        "address": "88, Sector 22, Noida",
        "blood_group": "AB-",
        "contact": "6655443322",
        "dob": "2013-01-22",
        "email": "arav@example.com",
        "father_contact": "6655443322",
        "father_name": "Dev Sharma",
        "grade": "Nursery",
        "joined_date": datetime(2023, 1, 15, 9, 15, 0),
        "mother_contact": "6655443322",
        "mother_name": "Rekha Sharma",
        "name": "Arav Sharma",
        "nick_name": "Aru",
        "parent_name": "Rekha Sharma",
        "profile_image": "",
        "student_id": "STU2025009",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👦",
        "date": today_str
    },
    {
        "address": "55, Ganga Nagar, Lucknow",
        "blood_group": "O+",
        "contact": "9900112233",
        "dob": "2014-10-30",
        "email": "sana@example.com",
        "father_contact": "9900112233",
        "father_name": "Mohd. Faizan",
        "grade": "Playgroup",
        "joined_date": datetime(2024, 4, 10, 8, 30, 0),
        "mother_contact": "9900112233",
        "mother_name": "Alia Faizan",
        "name": "Sana Faizan",
        "nick_name": "Sanu",
        "parent_name": "Alia Faizan",
        "profile_image": "",
        "student_id": "STU2025010",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👧",
        "date": today_str
    },
    {
        "address": "12, Hill View, Shimla",
        "blood_group": "B+",
        "contact": "7766554433",
        "dob": "2013-03-14",
        "email": "kabir@example.com",
        "father_contact": "7766554433",
        "father_name": "Anil Mehta",
        "grade": "Pre primary I",
        "joined_date": datetime(2023, 7, 20, 9, 0, 0),
        "mother_contact": "7766554433",
        "mother_name": "Maya Mehta",
        "name": "Kabir Mehta",
        "nick_name": "Kabu",
        "parent_name": "Maya Mehta",
        "profile_image": "",
        "student_id": "STU2025011",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👦",
        "date": today_str
    },
    {
        "address": "20, MG Road, Indore",
        "blood_group": "A+",
        "contact": "1231231234",
        "dob": "2012-06-17",
        "email": "tina@example.com",
        "father_contact": "1231231234",
        "father_name": "Sunil Bansal",
        "grade": "Playgroup",
        "joined_date": datetime(2023, 6, 25, 8, 0, 0),
        "mother_contact": "1231231234",
        "mother_name": "Neha Bansal",
        "name": "Tina Bansal",
        "nick_name": "Tinu",
        "parent_name": "Neha Bansal",
        "profile_image": "",
        "student_id": "STU2025012",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👧",
        "date": today_str
    },
    {
        "address": "76, Vivek Vihar, Jaipur",
        "blood_group": "B-",
        "contact": "9080706050",
        "dob": "2013-11-03",
        "email": "aditya@example.com",
        "father_contact": "9080706050",
        "father_name": "Dinesh Verma",
        "grade": "Nursery",
        "joined_date": datetime(2022, 12, 1, 9, 20, 0),
        "mother_contact": "9080706050",
        "mother_name": "Rachna Verma",
        "name": "Aditya Verma",
        "nick_name": "Adi",
        "parent_name": "Rachna Verma",
        "profile_image": "",
        "student_id": "STU2025013",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👦",
        "date": today_str
    },
    {
        "address": "45, Station Road, Nagpur",
        "blood_group": "AB+",
        "contact": "8007006005",
        "dob": "2015-01-27",
        "email": "riya@example.com",
        "father_contact": "8007006005",
        "father_name": "Karan Jain",
        "grade": "Pre primary I",
        "joined_date": datetime(2024, 3, 5, 10, 0, 0),
        "mother_contact": "8007006005",
        "mother_name": "Swati Jain",
        "name": "Riya Jain",
        "nick_name": "Riri",
        "parent_name": "Swati Jain",
        "profile_image": "",
        "student_id": "STU2025014",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👧",
        "date": today_str
    },
    {
        "address": "101, Nirmal Colony, Ranchi",
        "blood_group": "O-",
        "contact": "7776665554",
        "dob": "2014-02-18",
        "email": "yash@example.com",
        "father_contact": "7776665554",
        "father_name": "Naveen Prasad",
        "grade": "Playgroup",
        "joined_date": datetime(2023, 10, 12, 9, 10, 0),
        "mother_contact": "7776665554",
        "mother_name": "Anju Prasad",
        "name": "Yash Prasad",
        "nick_name": "Yashi",
        "parent_name": "Anju Prasad",
        "profile_image": "",
        "student_id": "STU2025015",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👦",
        "date": today_str
    },
    {
        "address": "24, Ashok Vihar, Delhi",
        "blood_group": "B+",
        "contact": "9012345678",
        "dob": "2013-02-10",
        "email": "arav1@example.com",
        "father_contact": "9012345678",
        "father_name": "Dev Sharma",
        "grade": "Nursery",
        "joined_date": datetime(2023, 2, 10, 9, 0, 0),
        "mother_contact": "9012345678",
        "mother_name": "Rekha Sharma",
        "name": "Arav Sharma",
        "nick_name": "Aru",
        "parent_name": "Rekha Sharma",
        "profile_image": "",
        "student_id": "STU2025016",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👦",
        "date": today_str
    },
    {
        "address": "58, Lakeview Colony, Bhopal",
        "blood_group": "A+",
        "contact": "9123456789",
        "dob": "2013-05-14",
        "email": "arav2@example.com",
        "father_contact": "9123456789",
        "father_name": "Dev Sharma",
        "grade": "Nursery",
        "joined_date": datetime(2023, 3, 12, 9, 45, 0),
        "mother_contact": "9123456789",
        "mother_name": "Rekha Sharma",
        "name": "Arav Sharma",
        "nick_name": "Aru",
        "parent_name": "Rekha Sharma",
        "profile_image": "",
        "student_id": "STU2025017",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👦",
        "date": today_str
    },
    {
        "address": "102, Garden Road, Surat",
        "blood_group": "O+",
        "contact": "9234567890",
        "dob": "2012-12-01",
        "email": "arav3@example.com",
        "father_contact": "9234567890",
        "father_name": "Dev Sharma",
        "grade": "Nursery",
        "joined_date": datetime(2023, 4, 5, 10, 30, 0),
        "mother_contact": "9234567890",
        "mother_name": "Rekha Sharma",
        "name": "Arav Sharma",
        "nick_name": "Aru",
        "parent_name": "Rekha Sharma",
        "profile_image": "",
        "student_id": "STU2025018",
        "attendance": "0/30",
        "inTime": "---",
        "outTime": "---",
        "isPresent": False,
        "avatar": "👦",
        "date": today_str
    }


]

# for student in students:
#     db.collection("students").add(student)

# print("20 new students with full fields imported to Firestore.")
students_ref = db.collection("students")
students_docs = students_ref.stream()

students_ref = db.collection("students")
students_docs = list(students_ref.stream())  # Firestore documents

for i, student_doc in enumerate(students_docs):
    student_data = student_doc.to_dict()
    student_id = student_data.get("student_id")

    if not student_id:
        print(f"Skipping document without student_id: {student_doc.id}")
        continue

    # Assign based on index
    if i < 3:
        assigned_month = "July"
    elif i < 8:
        assigned_month = "June"
    else:
        assigned_month = "May"

    # Use document ID from Firestore to update
    db.collection("students").document(student_doc.id).update({
        "last_paid_month": assigned_month
    })

    print(f"Updated {student_id} → last_paid_month = {assigned_month}")
